// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mekeqmzoguntcusxvcja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1la2VxbXpvZ3VudGN1c3h2Y2phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNDQ2MTIsImV4cCI6MjA2MzkyMDYxMn0.mbtj_y-qPxIwrp-84lgCCRfWBskdLCz8u3cEpcefrNI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);